From mongo:3.2.21-jessie
LABEL maintainer="453104950@qq.com"
MAINTAINER moxianran "453104950@qq.com"

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

