version: '3.7'
services:
  mysql-db:
        build: ./mysql
        ports:
          - "3307:3306"
        volumes:
          - ../data/mysql:/var/lib/mysql:rw
          - ../logs/mysql:/var/lib/mysql-logs:rw
          - ./mysql/conf.d:/etc/mysql/conf.d:ro
        environment:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: test123
          MYSQL_USER: test
          MYSQL_PASSWORD: 123456
        restart: always
        command: "--character-set-server=utf8"

  redis-db:
      build: ./redis
      ports:
        - "6379:6379"
      volumes:
        - ../data/redis:/data
      restart: always

  mongo:
      build: ./mongo
      ports:
        - 27017:27017
      volumes:
        - ../data/mongo/db:/data/db
        - ../data/mongo/dbconfigs:/data/dbconfigs
      environment:  # admin账号和密码
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: 123456
      restart: always

  php71:
    build: ./php/php71
    ports:
      - "9000:9000"
    volumes:
      - ../html/:/data/html/:rw
      - ./php/php71/php.ini:/usr/local/etc/php/php.ini:ro
      - ./php/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      #- ../logs/php-fpm:/var/log/php-fpm:rw
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    restart: always
    command: php-fpm

  php56:
      build: ./php/php56
      ports:
        - "9001:9000"
      volumes:
        - ../html/:/data/html/:rw
        - ./php/php56/php.ini:/usr/local/etc/php/php.ini:ro
        - ./php/php56/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
        #- ../logs/php-fpm:/var/log/php-fpm:rw
      links:
        - mysql-db:mysql-db
        - redis-db:redis-db
      restart: always
      command: php-fpm

  nginx:
    build: ./nginx
    depends_on:
      - php56
      - php71
    links:
      - php56:php56
      - php71:php71
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - ../html:/data/html:rw
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    restart: always
    command: nginx -g 'daemon off;' # 关闭守护进程执行




